import localFont from "next/font/local"
import "./globals.css"
import CustomProvider from "@/store/provider"
import { getServerSession } from "next-auth/next"
import { authOptions } from "@/lib/auth"
import SessionSync from "@/store/sessionsync"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomProvider session={session}>
          <SessionSync />
          {children}
        </CustomProvider>
      </body>
    </html>
  )
}